# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('bet_amount', models.IntegerField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
