# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='game',
            new_name='game_name',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_for',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
